# Generated by Django 3.1 on 2020-08-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='duration',
            field=models.IntegerField(default=1),
        ),
    ]
