# Generated by Django 3.1 on 2020-08-29 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_auto_20200829_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='extras',
            field=models.JSONField(default=dict),
        ),
    ]
